---
- name: create SonarQube directories
  file:
    path: "{{ user.software }}/{{ item }}"
    mode: 0700
    state: directory
    recurse: true
  with_items:
    - "{{ sonarqube.home }}"
    - "{{ sonarqube.home }}/extensions"
    - "{{ sonarqube.home }}/logs"
    - "{{ sonarqube.home }}/psql"
  tags: sonarqube

- name: create SonarQube docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ user.software }}/{{ sonarqube.home }}/docker-compose.yml"
  tags: sonarqube

- name: create SonarQube Makefile
  template:
    src: Makefile.j2
    dest: "{{ user.software }}/{{ sonarqube.home }}/Makefile"
  tags: sonarqube
