---
- name: create mpv config directory
  file:
    path: "~/{{ mpv.config.home }}"
    mode: 0700
    state: directory
  tags: mpv

- name: copy mpv config
  copy:
    src: config
    dest: "~/{{ mpv.config.home }}/config"
  tags: mpv
