---
- name: ensure github.com is a known host
  lineinfile:
    dest: "~/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  tags: github

- name: clone GitHub repositories
  git:
    repo: "git@github.com:sebhoss/{{ item }}.git"
    dest: "{{ user.git }}/{{ item }}"
  with_items: "{{ github.repositories }}"
  tags: github

- name: clone GitHub wiki repositories
  git:
    repo: "git@github.com:sebhoss/{{ item }}.wiki.git"
    dest: "{{ user.git }}/{{ item }}.wiki"
  with_items: "{{ github.wikis }}"
  tags: github
