all: help

help:
  @echo ""
  @echo "-- Help Menu"
  @echo ""
  @echo "   1. make start        - start Artifactory"
  @echo "   2. make stop         - stop Artifactory"
  @echo "   3. make logs         - view logs"
  @echo "   4. make purge        - stop and remove the container"

start:
  @echo "Starting Artifactory..."
  @docker-compose up -d
  @echo "Access Artifactory at: http://localhost:{{ artifactory.http.port }}/"
  @echo "Type 'make logs' for the logs"

stop:
  @echo "Stopping Artifactory..."
  @docker-compose stop

logs:
  @docker-compose logs

purge: stop
  @echo "Removing stopped container..."
  @docker-compose rm

.PHONY: all help start stop logs purge
