---
- name: create gnupg config directory
  file:
    path: "~/.gnupg"
    mode: 0700
    state: directory
  tags: gnupg

- name: copy gnupg settings
  copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item | basename }}"
  with_fileglob:
    - ./*
  notify:
     - gpg-agent
     - dirmngr
  tags: gnupg

- name: remove gnome autostarts
  file:
    path: "~/.config/autostart/{{ item }}"
    state: absent
  with_items:
    - gnome-keyring-gpg.desktop
    - gnome-keyring-ssh.desktop
  tags: gnupg
