---
- name: clone metio.wtf repositories
  git:
    repo: "{{ item.repository }}"
    dest: "{{ user.git }}/metio.wtf/{{ item.name }}"
  with_items: "{{ metio.projects }}"
  tags: metio

- name: setup metio.wtf push mirrors
  shell: "git remote set-url origin --push --add {{ item.1.location }} && touch {{ user.git }}/metio.wtf/{{ item.0.name }}/.ansible-git-mirror-{{ item.1.name }}"
  args:
    chdir: "{{ user.git }}/metio.wtf/{{ item.0.name }}"
    creates: "{{ user.git }}/metio.wtf/{{ item.0.name }}/.ansible-git-mirror-{{ item.1.name }}"
  with_subelements:
    - "{{ metio.projects }}"
    - mirrors
  tags: metio
