# {{ ansible_managed }}

.PHONY: all
all: help

.PHONY: all
help:
	@echo ""
	@echo "-- Help Menu"
	@echo ""
	@echo "   1. make start        - start Nexus"
	@echo "   2. make stop         - stop Nexus"
	@echo "   3. make logs         - view logs"
	@echo "   4. make purge        - stop and remove the container"

.PHONY: start
start:
	@docker-compose up -d

.PHONY: stop
stop:
	@docker-compose stop

.PHONY: logs
logs:
	@docker-compose logs --follow --tail=100

.PHONY: purge
purge: stop;
	@docker-compose rm
