---
- name: create git config directory
  file:
    path: "~/{{ git.config.home }}"
    mode: 0700
    state: directory
  tags: git

- name: create git config file
  template:
    src: gitconfig.j2
    dest: "~/{{ git.config.home }}/gitconfig"
  tags: git

- name: create git repository directory
  file:
    path: "{{ user.git }}"
    mode: 0700
    state: directory
  tags:
    - git

- name: create git group repository directories
  file:
    path: "{{ user.git }}/{{ item.group }}"
    mode: 0700
    state: directory
  with_items: "{{ projects }}"
  tags:
    - git

- name: clone git repositories
  git:
    repo: "{{ item.repository }}"
    dest: "{{ user.git }}/{{ item.group }}/{{ item.name }}"
  with_items: "{{ projects }}"
  tags: git

- name: setup git push mirrors
  shell: "git remote set-url origin --push --add {{ item.1.location }} && touch {{ user.git }}/{{ item.0.group }}/{{ item.0.name }}/.ansible-git-mirror-{{ item.1.name }}"
  args:
    chdir: "{{ user.git }}/{{ item.0.group }}/{{ item.0.name }}"
    creates: "{{ user.git }}/{{ item.0.group }}/{{ item.0.name }}/.ansible-git-mirror-{{ item.1.name }}"
  with_subelements:
    - "{{ projects }}"
    - mirrors
  tags: git
    