---
- name: create git config directory
  file:
    path: "~/{{ git.config.home }}"
    mode: 0700
    state: directory
  tags: git

- name: create git config file
  template:
    src: gitconfig.j2
    dest: "~/{{ git.config.home }}/gitconfig"
  tags: git

- name: create git repository directory
  file:
    path: "{{ user.git }}"
    mode: 0700
    state: directory
  tags:
    - git
    - bitbucket
    - github
