---
- name: download atom .deb package
  get_url:
    url: https://atom.io/download/deb
    dest: /tmp/atom.deb
  tags: atom

- name: install atom .deb package
  become: yes
  become_method: sudo
  apt:
    deb: /tmp/atom.deb
  tags: atom

- name: create atom config directory
  file:
    path: "{{ user.home }}/{{ atom.config.home }}"
    mode: 0700
    state: directory
  tags: atom

- name: copy atom config
  copy:
    src: "{{ item }}"
    dest: "{{ user.home }}/{{ atom.config.home }}/{{ item | basename }}"
  with_fileglob:
    - ./*
  tags: atom
