---
- name: ensure BitBucket is a known host
  lineinfile:
    dest: "{{ user.home }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket.\\.org"
  tags: bitbucket

- name: clone BitBucket repositories
  git:
    repo: "git@bitbucket.org:{{ user.name }}/{{ item }}.git"
    dest: "{{ user.git }}/{{ item }}"
  with_items: "{{ bitbucket.repositories }}"
  tags: bitbucket

- name: clone BitBucket wiki repositories
  git:
    repo: "git@bitbucket.org:{{ user.name }}/{{ item }}.git/wiki"
    dest: "{{ user.git }}/{{ item }}.wiki"
  with_items: "{{ bitbucket.wikis }}"
  tags: bitbucket
