# artifactory maven repository
alias artifactory='cd ~/Software/artifactory'
alias start-artifactory='artifactory && make start'
alias stop-artifactory='artifactory && make stop'
alias log-artifactory='artifactory && make logs'

# sonarqube code analytics
alias sonar='cd ~/Software/sonar'
alias start-sonar='sonar && make start'
alias stop-sonar='sonar && make stop'
alias log-sonar='sonar && make logs'

# ysura projects
alias sip='cd ~/Projects/ysura/SIP'
alias sip-repo='cd ~/Projects/ysura/SIP/repository/sip'

