---
- name: create Artifactory directories
  file:
    path: "{{ user.sofware }}/{{ item }}"
    mode: 0700
    state: directory
    recurse: true
  with_items:
    - "{{ artifactory.home }}"
    - "{{ artifactory.home }}/backup"
    - "{{ artifactory.home }}/data"
    - "{{ artifactory.home }}/logs"
  tags: artifactory

- name: create Artifactory docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ user.sofware }}/{{ artifactory.home }}/docker-compose.yml"
  tags: artifactory

- name: create Artifactory Makefile
  template:
    src: Makefile.j2
    dest: "{{ user.sofware }}/{{ artifactory.home }}/Makefile"
  tags: artifactory
